name: Bug Report
description: Report a bug to help us improve
title: "[Bug] "
labels: ["bug"]

body:
    - type: markdown
      id: description
      attributes:
          label: What happened?
          description: Include any necessary background information.
		  value: |
"## What happened and what's the expected result?

## Steps to Reproduce
"

    - type: checkboxes
      id: not-a-duplicate
      attributes:
          label: This is not a duplicate issue
          description: Search for duplicate issues in the [issues page](https://github.com/Mocha-Downloader/mocha-downloader/issues)
          options:
              - label: This is a unique issue, and is not a duplicate.
                required: true
      validations:
          required: true
