name: Publish

on:
    workflow_dispatch:
        inputs:
            version_tag:
                description: The version label to be used for this release
                required: true

jobs:
    publish:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn

            - name: Install dependencies
              run: yarn install

            - name: Publish releases
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn postinstall
                  yarn build
				  brew cask install wine-stable
                  yarn electron-builder --publish always --win --linux --mac
