name: Publish

# on: push

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: yarn

            - name: Install dependencies
              run: yarn install

            - name: Publish releases
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn postinstall
                  yarn build
                  yarn electron-builder -- --publish always --win --linux
